#!/bin/bash


for i in O0 O1 O2 O3 Os Ofast Og; do
        gcc -$i main.c -o main -lm
        echo "$i OPTIMIZATION LEVEL:" >> timeResults.txt

        for n in 4000000000 3000000000 2000000000; do
            echo "__Executing time for N = $n:" >> timeResults.txt
            for k in 1 2 3; do
            echo "$k:" >> timeResults.txt
            (time ./main $n) &>> timeResults.txt
            done
        done

        echo -e "#############################\n\n\n" >> timeResults.txt
done